twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'bootstrap_4_horizontal_layout.html.twig'
    globals:
        app_name:           '%env(APP_NAME)%'
        app_organization:   '%env(APP_ORGANIZATION)%'
        app_repository:     '%env(APP_REPOSITORY)%'
        app_force_user_for_code: '%env(bool:APP_FORCE_USER_FOR_CODE)%'

